// auth
export const AUTH_ERROR = "AUTH_ERROR";
export const CONFIRM_EXIT = "CONFIRM_EXIT";
// edit psych
export const EDIT_PSYCH_SUCCESS = "EDIT_PSYCH_SUCCESS";
export const EDIT_PSYCH_FAILED = "EDIT_PSYCH_FAILED";
// ban psych
export const BAN_PSYCH_SUCCESS = "BAN_PSYCH_SUCCESS";
export const BAN_PSYCH_FAILED = "BAN_PSYCH_FAILED";
// delete psych
export const CONFIRM_DELETE_PSYCH = "CONFIRM_DELETE_PSYCH";

export const DELETE_PSYCH_SUCCESS = "DELETE_PSYCH_SUCCESS";
export const DELETE_PSYCH_FAILED = "DELETE_PSYCH_FAILED";
// edit client
export const EDIT_CLIENT_SUCCESS = "EDIT_CLIENT_SUCCESS";
export const EDIT_CLIENT_FAILED = "EDIT_CLIENT_FAILED";
// ban client
export const BAN_CLIENT_SUCCESS = "BAN_CLIENT_SUCCESS";
export const BAN_CLIENT_FAILED = "BAN_CLIENT_FAILED";
// delete client
export const CONFIRM_DELETE_CLIENT = "CONFIRM_DELETE_CLIENT";

export const DELETE_CLIENT_SUCCESS = "DELETE_CLIENT_SUCCESS";
export const DELETE_CLIENT_FAILED = "DELETE_CLIENT_FAILED";
// connect psych to client
export const CONFIRM_CONNECT_PSYCH_TO_CLIENT =
  "CONFIRM_CONNECT_PSYCH_TO_CLIENT";

export const SUCCESS_CONNECT_PSYCH_TO_CLIENT =
  "SUCCESS_CONNECT_PSYCH_TO_CLIENT";
// make an appointment between the client and the psych
export const CONFIRM_MAKE_APPOINTMENT = "CONFIRM_MAKE_APPOINTMENT";
export const SUCCESS_MAKE_APPOINTMENT = "SUCCESS_MAKE_APPOINTMENT";

export const CONFIRM_EDIT_APPOINTMENT = "CONFIRM_EDIT_APPOINTMENT";
export const SUCCESS_EDIT_APPOINTMENT = "SUCCESS_EDIT_APPOINTMENT";

export const CONFIRM_ADD_PAYMENT = "CONFIRM_ADD_PAYMENT";
export const SUCCESS_ADD_PAYMENT = "SUCCESS_ADD_PAYMENT";
